### ISSUE TITLE
How to install and use orocos under Ubuntu without ROS successfully?

### ISSUE THREAD

**Issue by drscopus** [orocos-toolchain/orocos_toolchain#27]
Like the [autonomous car application](http://www.orocos.org/node/632) , I want to use orocos to build our robotic system without using ROS. So  I tried to install orocos under Ubuntu 14.04. I have tried three ways to install orocos.

Firstly, I followed the first part ["Installation: the easy way (linux) ](http://www.orocos.org/wiki/orocos/toolchain/quick-start-linux)" of the instructions on ​this page. 

I downloaded the bootstrap.sh script by
 "wget -O bootstrap-2.6.sh https://raw.githubusercontent.com/orocos-toolchain/build/master/bootstrap.sh"`. 

After running the command " sh bootstrap.sh", it came out
 `" Can't open /home/new/orocos/orocos-toolchain/env.sh". `

So I copied an env.sh script from the github of orocos-toolchain to the directory same to bootstrap.sh and re-run the command "sh bootstrap.sh". 
It came out 
```
autoproj failed to update your configuration. This means most of the time that there
was an temporary network problem. You can try to manually complete the bootstrap by
typing these three commands::
 . env.sh
 autoproj update
 autoproj fast-build
```
so I typed these three commands, it came out "autoproj: command not found".

Secondly, I followed the fourth part ["Installation: from zip/bz2/gz files"](http://www.orocos.org/wiki/orocos/toolchain/quick-start-linux)
I downloaded the orocos-toolchain-2.6.0-src.gz file from [this page](http://www.orocos.org/toolchain).   After running the command "./bootstrap_toolchain", 
it came out 
```
ERROR:  Error installing rdoc:
    rdoc requires Ruby version >= 2.2.2.
ERROR:  Error installing autobuild:
    rake requires Ruby version >= 2.0.0.
ERROR:  Error installing autoproj:
    rake requires Ruby version >= 2.0.0.
ERROR: failed to run gem1.9.1 install rdoc autobuild autoproj
ERROR: command output is: 
```

I installed ruby2.3 and re-run the command "./bootstrap_toolchain" , it came out 

```
autoproj: installing a proper Ruby environment (this can take a long time)
autoproj: installing autoproj and its dependencies (this can take a long time)
./bootstrap_toolchain:677:in `block in filter_uptodate_gems': undefined method `source_index' for Gem:Module (NoMethodError)
    from ./bootstrap_toolchain:675:in `delete_if'
    from ./bootstrap_toolchain:675:in `filter_uptodate_gems'
    from ./bootstrap_toolchain:974:in `install'
    from ./bootstrap_toolchain:1559:in `<main>'"
```
I googled these errors and have not found the solution. 

The last way I tried was by the instructions on [this page](https://github.com/orocos/rtt_ros_integration/).  However, this way is used for creating Orocos-ROS packages( I don't want to use ROS, because it is not hard real-time). Although building orocos from source was successfully done, the orocos commands and results on the orocos component builder's manual  can't be reproduced.

After creating HelloWorld by the orocos command “orocreate-pkg HelloWorld”, the errors came out by running the command "make" 
```
[rosbuild] Building package HelloWorld
[rosbuild] Error from directory check: /opt/ros/indigo/share/ros/core/rosbuild/bin/check_same_directories.py  /home/scopus/HelloWorld
1
Traceback (most recent call last):
  File "/opt/ros/indigo/share/ros/core/rosbuild/bin/check_same_directories.py", line 46, in <module>
    raise Exception
Exception
CMake Error at /opt/ros/indigo/share/ros/core/rosbuild/private.cmake:102 (message):
  [rosbuild] rospack found package "HelloWorld" at "", but the current
  directory is "/home/scopus/HelloWorld".  You should double-check your
  ROS_PACKAGE_PATH to ensure that packages are found in the correct
  precedence order.
Call Stack (most recent call first):
  /opt/ros/indigo/share/ros/core/rosbuild/public.cmake:177 (_rosbuild_check_package_location)
  /opt/ros/indigo/lib/cmake/orocos-rtt/UseOROCOS-RTT.cmake:54 (rosbuild_init)
  CMakeLists.txt:21 (include)
```

I also tried other commands "orocreate-catkin-pkg HelloWorld" and "make, but error "make: *** No targets specified and no makefile found.  Stop."

**Comment by roboticsai** [comment]
follow[ this ](https://github.com/orocos/rtt_ros_integration)steps to install orocos-toolchain.

**Comment by xwavex** [comment]
Not sure if this is too much, but we use the instructions from http://cogimon.github.io/runtime/gettingstarted.html which automatically installs Orocos as well as some other parts for robotics simulation and execution.

**Comment by roboticsai** [comment]
are u trying to install on xenomai patched linux kernel or normal linux kernel? if xenomai patched which version and how?

**Comment by drscopus** [comment]
@roboticsai Thank you for your advices!  I want to use OROCOS as independently as possible. But the orocos is combined with ROS in you suggested method.

**Comment by drscopus** [comment]
@roboticsai @xwavex  Thank you for your advices. My goal is for achieving a real time robot system. ROS is not a real time system for now. ROS2.0 is not available now. Are you sure that your methods can achieve a  real time robot system?

**Comment by roboticsai** [comment]
i'm using orocos only for low level control to interface hardware . i'm using ros only for using ros tools like rviz, gazebo, rqt etc. yes u can get hard real time capability with ros+orocos for that u have to use orocos in low level device interface which is integrated in hw interface code.

**Comment by drscopus** [comment]
Thank you for you reply! @roboticsai  would you like to show an example of your applications?

**Comment by roboticsai** [comment]
well u can find lot of projects and people using ros+orocos for their robotics projects to control their robot in hard real time. eg.  [http://rtt-lwr.readthedocs.io/en/latest/index.html](url) . i'm just starting on my own project named blackBird [here](https://github.com/roboticsai/blackBird_project), where i am using orocos for low level motion control in hard real time and ros for its ros_controllers and other tools live rviz , rqt which makes any robot related project easy and fast to develope.

**Comment by drscopus** [comment]
Thank you! Do I have to install xenomai? I have installed xenomai 2.6.5 in ubuntu 14.04 as this[ instructions.](http://rtt-lwr.readthedocs.io/en/latest/rtpc/xenomai.html). But it is not an official instructions, I am not sure that if the xenomai is configured correctly.

**Comment by drscopus** [comment]
On this [post of answers.ros](https://answers.ros.org/question/9330/a-hard-real-time-ros/), someone answered that:  "Everyone I have met here( KULeuven, home of OROCOS ) who is doing hard real-time is using Ubuntu with a xenomai kernel, ROS just as a package manager/build system, and writing all of their code as OROCOS components and running them in the orocos deployer".

So I wonder that whether using ROS is a negative factor for achieving (hard) real -time system or not.

**Comment by roboticsai** [comment]
no. just by using the ros build system with orocos, it doesn't affect the running rtt components. its answer is also given in some ros answer, u can search.

**Comment by onlyQF** [comment]
could you tell me how you solve this problem?

**Comment by meyerj** [comment]
It is perfectly fine to use an Orocos application for real-time control and interface it with other ROS nodes, e.g. for visualization or other tasks that are not real-time critical. Typically the latter is done using [rtt_ros_integration](https://github.com/orocos/rtt_ros_integration). The ROS communication does not affect the real-time components.

Regarding the installation problems: We added a new installation method which does not require Ruby or any other additional dependencies in #34. Please check the new top-level [README.md](https://github.com/orocos-toolchain/orocos_toolchain/blob/toolchain-2.9/README.md#get-started) for further details.

There are also plans to update the http://www.orocos.org/ web page soon and a bunch of new howtos and tutorials. Some instructions found there are outdated and do not work anymore on newer systems or with newer Orocos versions.

**Comment by drscopus** [comment]
I am not on this problem. I have not solved it yet.
