### ISSUE TITLE
Ruby Issues with Ubuntu 18.04 

### ISSUE THREAD

**Issue by lnnx2006** [orocos-toolchain/orocos_toolchain#29]
> Errors     << metaruby:cmake /home/fei/isir/orocos-2.9_ws/logs/metaruby/build.cmake.000.log                               
> CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
>   Could NOT find Ruby (missing: RUBY_INCLUDE_DIR RUBY_LIBRARY) (found version
>   "1.8.0")
> 

When catkin build with Ubuntu 18.04, the above problems will be encounted. Could anybody update the packages ?

**Comment by mjbogusz** [comment]
I've encountered that too while building `orocos_toolchain` in a catkin workspace, specifically when building `orogen`.
My workaround (but not a solution) was to manually call `cmake`:
```sh
cd [ws]/build/orogen
cmake ../../src/orocos/orocos_toolchain/orogen
cd ../..
catkin build [args]
```

**Comment by keivanzavari** [comment]
Hi

doing the `gem install rake hoe` solves the issue here... It's just that I have to open a new terminal which sources bashrc which contains setup.bash of ros and my catkin_ws

cmake version 3.10.2
gcc 7.3.0
ubuntu 18.04.1

**Comment by mjbogusz** [comment]
I've traced the issue back to its origin and filed a more precise bug report here: orocos-toolchain/utilrb#41.
Basically `RUBYOPT=-rubygems` is not anymore valid for Ruby >= 2.5 and it's best to remove it altogether.

If there's no PR by Monday I'll create my own - one for `utilrb`, and one for `orocos_toolchain` fixing the flag and updating the utilrb git submodule.

**Comment by mjbogusz** [comment]
utilrb PR: orocos-toolchain/utilrb#42
orocos_toolchain PR that apparently fixes this flag too: #13

**Comment by kaixqu** [comment]
Did you succeed in installing orogen? I just cannot find out how. Could you please help me? Thanks a lot. :-)

**Comment by meyerj** [comment]
The `RUBYOPT` bug was fixed in https://github.com/orocos-toolchain/utilrb/pull/42.

#13 was replaced by a new installation method based on pure CMake in #34, which does not depend on catkin. Please check the new top-level [README.md](https://github.com/orocos-toolchain/orocos_toolchain/blob/toolchain-2.9/README.md#get-started) for further details.
