### ISSUE TITLE
Compiling from sources ubuntu 18.04 fails (toolchain-2.9)

### ISSUE THREAD

**Issue by haianos** [orocos-toolchain/orocos_toolchain#31]
Fails on check gcc version "7" (note, it shold be g++, not gcc..)

```
git clone -b toolchain-2.9 --single-branch --recursive https://github.com/orocos-toolchain/orocos_toolchain.git src/orocos/orocos_toolchain
catkin_make_isolated --install
```

**Comment by meyerj** [comment]
The `toolchain-2.9` and other branches in this repo are not always up-to-date with the respective branches in all submodules. In this particular case the submodule `rtt` was still pointing to an older revision which did  not include https://github.com/orocos-toolchain/rtt/pull/200 yet.

Fixed in cb7c8d0. Could you verify, please?

**Comment by meyerj** [comment]
Updating submodules to the latest revision of the `toolchain-2.9` branch would have been another option:
```
git submodule update --remote --recursive
```

**Comment by meyerj** [comment]
RTT compiles successfully with some warnings, but `ocl/lua/tlsf.c` fails with the following error:
```
[ 30%] Building C object lua/CMakeFiles/tlsf_rtt.dir/tlsf.c.o
/home/ros/orocos_ws/core/src/orocos/orocos_toolchain/ocl/lua/tlsf.c: In function ‘FIND_SUITABLE_BLOCK’:
/home/ros/orocos_ws/core/src/orocos/orocos_toolchain/ocl/lua/tlsf.c:351:47: error: left shift of negative value [-Werror=shift-negative-value]
     u32_t _tmp = _tlsf->sl_bitmap[*_fl] & (~0 << *_sl);
                                               ^~
/home/ros/orocos_ws/core/src/orocos/orocos_toolchain/ocl/lua/tlsf.c:358:46: error: left shift of negative value [-Werror=shift-negative-value]
         *_fl = ls_bit(_tlsf->fl_bitmap & (~0 << (*_fl + 1)));
                                              ^~
cc1: all warnings being treated as errors
make[2]: *** [lua/CMakeFiles/tlsf_rtt.dir/tlsf.c.o] Error 1
lua/CMakeFiles/tlsf_rtt.dir/build.make:62: recipe for target 'lua/CMakeFiles/tlsf_rtt.dir/tlsf.c.o' failed
CMakeFiles/Makefile2:2178: recipe for target 'lua/CMakeFiles/tlsf_rtt.dir/all' failed
make[1]: *** [lua/CMakeFiles/tlsf_rtt.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```
`ocl` enables `-Werror` for target `rtt_tlsf` at [ocl/lua/CMakeLists.txt:96](https://github.com/orocos-toolchain/ocl/blob/toolchain-2.9/lua/CMakeLists.txt#L96). The same warning is emitted during compilation of tlsf in rtt, but is is not treated as error.

**Comment by haianos** [comment]
Thanks @meyerj ! I have verified and I have hit the same into the same issue...
Any hints for a solution?
Do you suggest to turn off `-Werror`..?

Just FYI, I tried on the same configuration to compile TLSF stand-alone (2.4.6, same version), and no warnings are raised.

**Comment by JimmyDaSilva** [comment]
@meyerj I am stuck on this one too.
Is it okay to ignore the error ?

**Comment by JimmyDaSilva** [comment]
@meyerj @haianos 
For now, a simple cast does the trick:
`    u32_t _tmp = _tlsf->sl_bitmap[*_fl] & (~((u32_t)0) << *_sl);`

**Comment by JimmyDaSilva** [comment]
Thanks, fixed with https://github.com/orocos-toolchain/ocl/pull/80
