### ISSUE TITLE
orogen fails to find metaruby

### ISSUE THREAD

**Issue by dustingooding** [orocos-toolchain/orocos_toolchain#44]
A recent PR on orogen resolved this issue. Maybe updating the orogen submodule version is appropriate now?  https://github.com/orocos-toolchain/orogen/pull/140

**Comment by dustingooding** [comment]
potential fix: https://github.com/orocos-toolchain/orogen/pull/143

edit: after I updated [my fork of _this_ repo](https://github.com/dustingooding/orocos_toolchain) to point to the commits I added in my PR above, metaruby was found and the compilation process finished as expected.  so i think this is an actual fix, not just a potential one.

**Comment by dustingooding** [comment]
https://github.com/orocos-toolchain/orocos_toolchain/pull/45 seems to be the fix

**Comment by meyerj** [comment]
> #45 seems to be the fix

So I assume this has been solved.
