### ISSUE TITLE
Add multi-platform Travis config

### ISSUE THREAD

**Issue by jbohren** [orocos-toolchain/orocos_toolchain#8]
Travis now supports multiple platforms for single repos, so we could take advantage of this to make sure less popular platforms continue to build: http://blog.travis-ci.com/2014-05-13-multi-os-feature-available/

Related to https://github.com/orocos-toolchain/ocl/issues/8

**Comment by meyerj** [comment]
This has been done in https://github.com/orocos-toolchain/orocos_toolchain/pull/34, but in the meantime Travis is obsolete already, or at least the builds on [travis-ci.com](https://app.travis-ci.com/github/orocos-toolchain/orocos_toolchain) fail due to insufficient credit at the moment.
